apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: default

resources:
- ./deployment.yaml
- ./service.yaml
- ./ingress.yaml
- ./sealed-secret/sealed-secret-env.yaml
- ./sealed-secret/sealed-secret-tls.yaml

images:
- name: wadam
  newName: ghcr.io/chrom9103/wadam
  newTag: 1.1.4
